modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/shedaniel/LightOverlay/issues/" #optional
logoFile = "icon.png"
authors = "shedaniel"
license = "Apache-2.0"
[[mods]]
modId = "lightoverlay"
version = "${version}"
displayName = "Light Overlay"
description = '''
To provide users with NEI-like light overlay.
'''

[[dependencies.lightoverlay]]
modId = "cloth_config"
type = "required"
versionRange = "[12,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lightoverlay]]
modId = "architectury"
type = "required"
versionRange = "[10,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lightoverlay]]
modId = "neoforge"
type = "required"
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "lightoverlay-neoforge.mixins.json"
